#!/bin/bash

echo "🚀 GET HTTPS FOR LINEAR WEBHOOK - IMMEDIATE SOLUTIONS"
echo "======================================================"

echo ""
echo "📋 OPTION 1: Cloudflare Tunnel (Recommended)"
echo "--------------------------------------------"
echo "Run these commands:"
echo ""
echo "1. Login (opens browser):"
echo "   cloudflared tunnel login"
echo "   → Select 'orangedoorhouse.com' zone"
echo ""
echo "2. Create tunnel:"
echo "   cloudflared tunnel create orange-hr-dashboard"
echo ""
echo "3. Configure DNS:"
echo "   cloudflared tunnel route dns orange-hr-dashboard hr.orangedoorhouse.com"
echo ""
echo "4. Start tunnel:"
echo "   cloudflared tunnel --url http://localhost:3003 run orange-hr-dashboard"
echo ""
echo "🎯 Result: https://hr.orangedoorhouse.com"
echo ""

echo "📋 OPTION 2: Check Render.com Status"
echo "------------------------------------"
echo "1. Go to: https://dashboard.render.com"
echo "2. Check service: 'orange-hr-dashboard-api'"
echo "3. If 'Live', copy URL"
echo "4. Test: curl https://YOUR-URL.onrender.com/health"
echo ""
echo "🎯 Result: https://orange-hr-dashboard-api.onrender.com"
echo ""

echo "📋 OPTION 3: Ngrok (Quickest)"
echo "-----------------------------"
echo "1. Sign up: https://ngrok.com (free)"
echo "2. Get authtoken from dashboard"
echo "3. Run:"
echo "   ngrok config add-authtoken YOUR_TOKEN"
echo "   ngrok http 3003"
echo ""
echo "🎯 Result: https://abc123.ngrok.io"
echo ""

echo "📋 OPTION 4: Local HTTPS Test"
echo "----------------------------"
echo "1. Install mkcert:"
echo "   brew install mkcert"
echo "2. Create certs:"
echo "   mkcert -install"
echo "   mkcert localhost"
echo "3. Test with Linear (may reject self-signed)"
echo ""
echo "🎯 Result: https://localhost:3443"
echo ""

echo "🚀 RECOMMENDED: Cloudflare Tunnel"
echo "---------------------------------"
echo "Takes 2 minutes, gives professional domain."
echo ""
echo "Run Option 1 commands now!"